CREATE TABLE STUDENT_MASTER
(
STUDENT_ID INTEGER NOT NULL PRIMARY KEY,
S_FNAME VARCHAR(40) NOT NULL,
S_LNAME VARCHAR(40) NOT NULL,
S_EMAILID VARCHAR(30) NOT NULL,
E_PHONE_NO VARCHAR(20) NOT NULL,
S_BIRTHDATE DATE NOT NULL,
S_CITY VARCHAR(30) NOT NULL,
S_STATE VARCHAR(30) NOT NULL,
S_COUNTRY VARCHAR(30) NOT NULL,
CATEGORY_ID INTEGER NOT NULL,
ACAD_STATUS_ID INTEGER NOT NULL
);
CREATE TABLE ENQUIRY_MASTER
(
ENQUIRY_ID INTEGER NOT NULL PRIMARY KEY,
ENQUIRY_DATE DATE NOT NULL,
STUDENT_ID INTEGER NOT NULL,
EXPERT_ID INTEGER NOT NULL
);
CREATE TABLE STATUS_MASTER
(
ACAD_STATUS_ID INTEGER NOT NULL PRIMARY KEY,
S_STATUS VARCHAR(30) NOT NULL,
);
CREATE TABLE CATEGORY_MASTER
(
CATEGORY_ID INTEGER NOT NULL PRIMARY KEY,
CATEGORY_DESCRIPTION VARCHAR(30) NOT NULL,
);
CREATE TABLE TEST_MASTER
(
TEST_ID INTEGER NOT NULL PRIMARY KEY,
TEST_TYPE_ID INTEGER NOT NULL,
);

DROP TABLE TEST_MASTER;

CREATE TABLE EXPERT_MASTER
(
EXPERT_ID INTEGER NOT NULL PRIMARY KEY,
E_FNAME VARCHAR(40) NOT NULL,
E_LNAME VARCHAR(40) NOT NULL,
E_EMAILID VARCHAR(30) NOT NULL,
E_WEBSITE VARCHAR(100) NOT NULL,
E_PHONE_NO VARCHAR(20) NOT NULL,
CATEGORY_ID INTEGER NOT NULL,
);
CREATE TABLE LOGIN_MASTER
(
USER_ID INTEGER NOT NULL PRIMARY KEY,
USERNAME VARCHAR(40) NOT NULL,
U_PASSWORD VARCHAR(40) NOT NULL,
);
CREATE TABLE QUESTION_MASTER
(
QUESTION_ID INTEGER NOT NULL PRIMARY KEY,
QUESTIONS VARCHAR(255) NOT NULL,
CORRECT_ANSWER_ID INTEGER NOT NULL,
);
CREATE TABLE TEST_TYPE_MASTER
(
TEST_TYPE_ID INTEGER NOT NULL PRIMARY KEY,
TYPE_DESCRIPTION VARCHAR(50) NOT NULL,
);
CREATE TABLE TEST_EVALUATION_MASTER
(
TEST_EVALUATION_ID INTEGER NOT NULL PRIMARY KEY,
TEST_SCORE VARCHAR(50) NOT NULL,
TEST_DATE DATE NOT NULL,
STUDENT_ID INTEGER NOT NULL,
TEST_ID INTEGER NOT NULL,
);

DROP TABLE TEST_EVALUATION_MASTER;

CREATE TABLE TEST_QUESTION_MAPPING
(
MAPPING_ID INTEGER NOT NULL PRIMARY KEY,
TEST_ID INTEGER NOT NULL,
QUESTION_ID INTEGER NOT NULL,
);
CREATE TABLE OPTION_MASTER
(
OPTION_ID INTEGER NOT NULL PRIMARY KEY,
OPTIONS VARCHAR(50) NOT NULL,
);
